#This works for container to container
#Simple cluster IP
apiVersion: v1
kind: Service
metadata:
  name: alpine-pyserv
  namespace: quick-test
spec:
  clusterIP: 10.96.0.100 #This is optional. Usually autoallocated. Use this only if you wish to have a specific point of entry for the client
  ports:
    - protocol : TCP
      port: 7000
      targetPort: 5000
  selector:
    app: alpserv-app
